baseURL = "https://bolajiayodeji.com/"
languageCode = "en-us"
title = "Bolaji Ayodeji"
theme = "hugo-lamp"
googleAnalytics = "UA-123719673-3"          # Google Analytics UA number

[params]
  titleName = "Hi, I'm Bolaji."
  subtitle = "I create contents around web and frontend development."
  portfolio = "About Me â†’"
  author = "Bolaji Ayodeji"
  logo = "https://res.cloudinary.com/iambeejayayo/image/upload/v1547954566/fav-500.png"
  description = "Articles on web & frontend development, all written by Bolaji Ayodeji. ðŸš€"
  paginate = 15

  # Addthis
  addThis = "ra-5c60f134dfdba39d"

  # Publisher
  ## adsensePublisher = "ca-pub-XXX"    # Required if you want to include Google Adsense
  adsenseSlot = "XXX"                   # Required slot to display ads
  adsenseSlotSticky = "XXX"             # Enables sticky ads feature, value maybe the same with adsenseSlot, remove if you don't want display sticky ads

  # SEO configs
  seotitle = "Bolaji Ayodeji"
  googleSiteVerification = "3BSMr7WxHkkxpM0Kfol42yWYvocFLiKQ3GPjsUSYnuk"    # Google Webmaster
  msValidate = "bing_site_verification_code"                  # Bing Webmaster

  # Social networks
  github = "bolajiayodeji"
  linkedin = "iambolajiayo"
  instagram = "iambolajiayo"
  youtube = "UCpFxuQyjQYal738TW0TJUNw"


[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Search"
  weight = 2
  identifier = "search"
  url = "/search"
[[menu.main]]
  name = "Newsletter"
  weight = 3
  identifier = "news"
  url = "https://tinyletter.com/bolajiayodeji/"
