baseURL = "https://bolajiayodeji.com/"
languageCode = "en-us"
title = "âš¡ï¸Bolaji Ayodejiâš¡ï¸"
theme = "hugo-lamp"
googleAnalytics = "UA-123719673-3"          # Google Analytics UA number

[params]
  titleName = "Hi, I'm Bolaji."
  subtitle = "I write articles on web and frontend development. ğŸš€"
  portfolio = "View portfolio â†’"
  author = "âš¡ï¸Bolaji Ayodejiâš¡ï¸"
  logo = "https://res.cloudinary.com/iambeejayayo/image/upload/v1547954566/fav-500.png"
  description = "Articles on Web & Frontend Development. âš¡ï¸âš¡ï¸ All written by Bolaji Ayodeji. ğŸš€"
  paginate = 15

  # Addthis
  addThis = "ra-5c60f134dfdba39d"

  # Publisher
  ## adsensePublisher = "ca-pub-XXX"    # Required if you want to include Google Adsense
  adsenseSlot = "XXX"                   # Required slot to display ads
  adsenseSlotSticky = "XXX"             # Enables sticky ads feature, value maybe the same with adsenseSlot, remove if you don't want display sticky ads

  # SEO configs
  seotitle = "Bolaji Ayodeji"
  googleSiteVerification = "3BSMr7WxHkkxpM0Kfol42yWYvocFLiKQ3GPjsUSYnuk"    # Google Webmaster
  msValidate = "bing_site_verification_code"                  # Bing Webmaster

  # Social networks
  github = "bolajiayodeji"
  linkedin = "iambolajiayo"
  instagram = "iambolajiayo"
  youtube = "UCpFxuQyjQYal738TW0TJUNw"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  blog = ["HTML", "JSON", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Home ğŸ "
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About Me ğŸ˜Š"
  weight = 2
  identifier = "portfolio"
  url = "/portfolio/"
[[menu.main]]
  name = "Resume ğŸ“"
  weight = 3
  identifier = "resume"
  url = "/portfolio/resume.pdf/"
[[menu.main]]
  name = "Projects ğŸ‘¨â€ğŸ’»"
  weight = 4
  identifier = "projects"
  url = "https://github.com/bolajiayodeji"
[[menu.main]]
  name = "Newsletter ğŸ“©"
  weight = 5
  identifier = "news"
  url = "https://eepurl.com/geCCfL"
